services:
  - type: web
    name: mi-api-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FIREBASE_CONFIG
        sync: false # Aquí pegaremos el contenido del JSON más tarde